export const constants = {
  actions: {
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    ADD_TODO_NEW: 'ADD_TODO_NEW',
    SET_INITIAL_TODOS: 'SET_INITIAL_TODOS',
    SET_INITIAL_TODO: 'GET_INITIAL_TODO',
    CHANGE_VISIBILITY_FILTER: 'CHANGE_VISIBILITY_FILTER',
    DELETE_TODO: 'DELETE_TODO',
    EDIT_TODO: 'EDIT_TODO'
  },
  SHOW_ALL: 'SHOW_ALL'
};
